language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install: echo "Install step ..."

script: echo "Script step ..." && true

before_deploy :
  - zip -r package.zip *
  - mkdir -p target
  - mv package.zip target

